### ISSUE TITLE
Use Github Pages

### ISSUE THREAD

**Issue by willianjusten** [barbier/mana-calc#1]
You should put this code in a Demo Page using a gh-pages branch =)

**Comment by barbier** [comment]
I'll try! 
I just need to understand how I'm going to have a Github page to this project and my blog at the same time!

**Comment by willianjusten** [comment]
When you create another project at gh-pages branch that it's different from your "username.github.io" it turns into "username.github.io/project-name" =)

**Comment by barbier** [comment]
Oh, nice!
Since I wanted to release it ASAP, I released the project without the page, but I'll do it on the next days.
Thanks for the feedback! =)

**Comment by willianjusten** [comment]
=)

**Comment by barbier** [comment]
Okay, it was really easy to do, I though I had to manually create the branch e do some stuff.... page is on!

**Comment by willianjusten** [comment]
=)
