### ISSUE TITLE
Remove jQuery dependecie

### ISSUE THREAD

**Issue by thiamsantos** [barbier/mana-calc#2]
@barbier you might use just vanilla js at the code. If you want I can do this for you.

**Comment by barbier** [comment]
@thiamsantos, I think it's not the time right now... I really think a code refactor it's going to be better right now, but we can remove jQuery later! =)

**Comment by thiamsantos** [comment]
Of course,  make sense. But for me,  the code has not much complexity to jQuery. So I will wait for the code refactoring. :)

**Comment by barbier** [comment]
Actually I used jQuery because I was lazy to make all the dom requisitions with vanilla XD
But with the code refactored it's going to be waaaay more easy to remove jQuery.
Thank you for the suport :)

**Comment by barbier** [comment]
Done in [commit c3bfbb7](https://github.com/barbier/mana-calc/commit/c3bfbb7f226739187567a040abbcd631ec2195d0).
